// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmdvpjoathkyehusnlfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZHZwam9hdGhreWVodXNubGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM2MzAsImV4cCI6MjA2NTQ2OTYzMH0.c2_9XwEhH8UPOwBIyI4MPHI5kLn8jjqeM32SuyT_q30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);